name: CICD

on:
  workflow_dispatch:
  
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        run: echo "Cloning the code"
      
    
  build:
    runs-on: ubuntu-latest
    needs: [code]
    steps:
      - name: building the code 
        run : echo "Building the code"
    
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: testing the code
        run: echo "Code is testing"
    
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: deploying code on ubuntu
        run: echo "Code is deployed"
    
  
