name : linter

on:
  workflow_dispatch: 

jobs:
  auto-linter:
    runs-on: ubuntu-latest
    steps:
      - name: code clone
        uses: actions/checkout@v7
      - name: Install linter
        run: pip install ruff
      - name: linting code
        run: ruff check .
      - name: successful message
        run: echo "Linting is successfully completed and no errors found"
